export const URL_PRODUCTS = 'http://localhost:3001/api/products/';
export const URL_CATEGORIES = 'http://localhost:3001/api/category/';
export const URL_PRODUCTS_BY_CATEGORY = 'http://localhost:3001/api/products/category/';
export const URL_PRODUCTS_BY_SEARCH = 'http://localhost:3001/api/products/search?name=';
export const URL_USERS = 'http://localhost:3001/api/user/';
export const URL_ORDERS_BY_ID = 'http://localhost:3001/api/order/';
export const URL_CART = 'http://localhost:3001/api/order/';
export const URL_GET_CART = 'http://localhost:3001/api/user/';
export const URL_GET_STATS = 'http://localhost:3001/api/order/analytics';
